version: "3"
services:
  db:
    image: mysql:8.0
    container_name: portforio-db
    environment:
      MYSQL_ROOT_PASSWORD: password
    ports:
      - "3306:3306"
    command: --default-authentication-plugin=mysql_native_password
    volumes:
      - mysql-data:/var/lib/mysql
  web:
    build: .
    container_name: portforio-web
    command: bundle exec rdebug-ide --host 0.0.0.0 --port 1234 --dispatcher-port 26162 -- bin/rails server -b 0.0.0.0
    volumes:
      - .:/myapp
    ports:
      - "3000:3000"
      - 1234:1234
      - 26162:26162
    depends_on:
      - db
    stdin_open: true
    tty: true
volumes:
  mysql-data:
    driver: local
